spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  application:
    name: VollMed
  datasource:
    url: jdbc:mysql://localhost:3306/prueba
    username: root
    password: 240605
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    baseline-on-migrate: true
    enabled: true

  web:
    error:
      include-stacktrace: never

server:
  error:
    include-message: always
    include-binding-errors: always

api:
  security:
    token:
      secret: 12345678